# Generated by Django 5.2.12 on 2026-03-05 01:34

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group', chained_model_field='group', on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
