# Generated by Django 5.2.12 on 2026-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_group_alter_question_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], default=1),
        ),
    ]
