events {}

http {

    include /etc/nginx/mime.types;

    server {

        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        # frontend
        location / {
            try_files $uri $uri/ /index.html;
        }

        # django static
        location /static/ {
            alias /app/staticfiles/;
        }

        # API
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # admin
        location /programmist-admin/ {
            proxy_pass http://backend:8000/programmist-admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }

}